# Generated by Django 4.2.7 on 2026-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0003_sync_testcase_generation_task_stream_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequirement',
            name='case_generation_status',
            field=models.CharField(choices=[('not_generated', '未生成'), ('generating', '生成中'), ('generated', '已生成'), ('failed', '生成失败')], default='not_generated', max_length=20, verbose_name='用例生成状态'),
        ),
    ]
