# Generated by Django 4.2.7 on 2026-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0004_businessrequirement_case_generation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequirement',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', verbose_name='验收标准'),
        ),
    ]
