# Generated by Django 4.2.7 on 2026-04-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0005_alter_businessrequirement_acceptance_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequirement',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='requirement_analysis.requirementanalysis', verbose_name='关联分析'),
        ),
    ]
