# Generated by Django 4.2.7 on 2026-04-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
