# Generated by Codex on 2026-05-28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvironment',
            name='account',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='账号'),
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='password_encrypted',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='密码(加密存储)'),
        ),
        migrations.AddField(
            model_name='projectenvironment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='base_url',
            field=models.URLField(max_length=500, verbose_name='基础URL'),
        ),
        migrations.AlterModelOptions(
            name='projectenvironment',
            options={
                'ordering': ['project__name', '-is_default', 'name', 'id'],
                'verbose_name': '项目环境',
                'verbose_name_plural': '项目环境',
            },
        ),
    ]
