# Generated by Django 4.2.7 on 2026-03-30 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0002_initial"),
        ("ui_automation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRunUiAutomationBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("engine", models.CharField(choices=[("playwright", "Playwright"), ("selenium", "Selenium")], default="playwright", max_length=20, verbose_name="执行引擎")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "未生成"),
                            ("generating", "生成中"),
                            ("pending_review", "待审核"),
                            ("partially_approved", "部分已审核"),
                            ("approved", "已审核"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("generation_summary", models.JSONField(blank=True, default=dict, verbose_name="生成摘要")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_execution_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "generated_suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_batches",
                        to="ui_automation.testsuite",
                        verbose_name="生成套件",
                    ),
                ),
                (
                    "last_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_batches",
                        to="ui_automation.testexecution",
                        verbose_name="最近执行记录",
                    ),
                ),
                (
                    "target_ui_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_batches",
                        to="ui_automation.uiproject",
                        verbose_name="目标 UI 项目",
                    ),
                ),
                (
                    "test_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_automation_batch",
                        to="executions.testrun",
                        verbose_name="测试执行",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_execution_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "db_table": "test_run_ui_automation_batches",
                "verbose_name": "执行 UI 自动化批次",
                "verbose_name_plural": "执行 UI 自动化批次",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRunUiAutomationCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="候选用例名称")),
                ("description", models.TextField(blank=True, verbose_name="候选描述")),
                ("preconditions", models.TextField(blank=True, verbose_name="前置条件")),
                ("priority", models.CharField(default="medium", max_length=10, verbose_name="优先级")),
                ("source_snapshot", models.JSONField(blank=True, default=dict, verbose_name="源用例快照")),
                ("steps_data", models.JSONField(blank=True, default=list, verbose_name="候选步骤")),
                ("step_count", models.PositiveIntegerField(default=0, verbose_name="步骤数")),
                (
                    "review_status",
                    models.CharField(
                        choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已驳回")],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "generation_source",
                    models.CharField(
                        choices=[("ai", "AI"), ("heuristic", "规则")],
                        default="ai",
                        max_length=20,
                        verbose_name="生成来源",
                    ),
                ),
                ("generation_error", models.TextField(blank=True, verbose_name="生成告警")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="审核时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="executions.testrunuiautomationbatch",
                        verbose_name="批次",
                    ),
                ),
                (
                    "generated_test_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_candidates",
                        to="ui_automation.testcase",
                        verbose_name="落地 UI 用例",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_execution_candidates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "run_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_automation_candidate",
                        to="executions.testruncase",
                        verbose_name="执行用例",
                    ),
                ),
            ],
            options={
                "db_table": "test_run_ui_automation_candidates",
                "verbose_name": "执行 UI 自动化候选",
                "verbose_name_plural": "执行 UI 自动化候选",
                "ordering": ["run_case__id"],
            },
        ),
    ]
