# Generated by Django 4.2.7 on 2026-03-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0003_test_run_ui_automation"),
        ("testcases", "0002_initial"),
        ("ui_automation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseUiAutomationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("engine", models.CharField(choices=[("playwright", "Playwright"), ("selenium", "Selenium")], default="playwright", max_length=20, verbose_name="执行引擎")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "未生成"),
                            ("generating", "生成中"),
                            ("pending_review", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("failed", "失败"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255, verbose_name="候选用例名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="候选描述")),
                ("preconditions", models.TextField(blank=True, default="", verbose_name="前置条件")),
                ("priority", models.CharField(default="medium", max_length=10, verbose_name="优先级")),
                ("source_snapshot", models.JSONField(blank=True, default=dict, verbose_name="源用例快照")),
                ("steps_data", models.JSONField(blank=True, default=list, verbose_name="候选步骤")),
                ("step_count", models.PositiveIntegerField(default=0, verbose_name="步骤数")),
                ("review_comment", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "generation_source",
                    models.CharField(
                        choices=[("ai", "AI"), ("heuristic", "规则")],
                        default="ai",
                        max_length=20,
                        verbose_name="生成来源",
                    ),
                ),
                ("generation_error", models.TextField(blank=True, verbose_name="生成告警")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="审核时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_testcase_ui_automation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "generated_test_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testcase_ui_automation_records",
                        to="ui_automation.testcase",
                        verbose_name="落地 UI 用例",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_testcase_ui_automation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "source_testcase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_automation_record",
                        to="testcases.testcase",
                        verbose_name="源测试用例",
                    ),
                ),
                (
                    "target_ui_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testcase_ui_automation_records",
                        to="ui_automation.uiproject",
                        verbose_name="目标 UI 项目",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_testcase_ui_automation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "db_table": "testcase_ui_automation_records",
                "verbose_name": "测试用例 UI 自动化记录",
                "verbose_name_plural": "测试用例 UI 自动化记录",
                "ordering": ["-updated_at"],
            },
        ),
    ]
