# Generated by Django 4.2.7 on 2026-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_testcase_ui_automation_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
    ]
