# Generated by Django 4.2.7 on 2026-04-09 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTestCaseMindmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='脑图名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('mindmap_data', models.JSONField(default=dict, verbose_name='脑图数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_mindmaps', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_mindmaps', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '手工用例脑图',
                'verbose_name_plural': '手工用例脑图',
                'db_table': 'manual_testcase_mindmaps',
                'ordering': ['-updated_at'],
            },
        ),
    ]
