# Generated by Django 4.2.7 on 2026-04-13 01:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('testcases', '0003_manualtestcasemindmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTestCaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目录名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testcases.manualtestcasecategory', verbose_name='父目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_categories', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '手工用例目录',
                'verbose_name_plural': '手工用例目录',
                'db_table': 'manual_testcase_categories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
