# Generated by Codex on 2026-04-14

from django.db import migrations, models
import django.db.models.deletion


def bind_existing_mindmaps_to_root(apps, schema_editor):
    ManualTestCaseCategory = apps.get_model('testcases', 'ManualTestCaseCategory')
    ManualTestCaseMindmap = apps.get_model('testcases', 'ManualTestCaseMindmap')

    project_ids = set(ManualTestCaseMindmap.objects.values_list('project_id', flat=True))
    project_ids.update(ManualTestCaseCategory.objects.values_list('project_id', flat=True))

    for project_id in project_ids:
        if not project_id:
            continue

        root_category = ManualTestCaseCategory.objects.filter(
            project_id=project_id,
            parent__isnull=True,
            name='物业通'
        ).order_by('id').first()

        if not root_category:
            root_category = ManualTestCaseCategory.objects.create(
                project_id=project_id,
                name='物业通',
                description='手工用例根目录',
                order=0,
            )

        ManualTestCaseMindmap.objects.filter(
            project_id=project_id,
            category__isnull=True,
        ).update(category_id=root_category.id)


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_manualtestcasecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='mindmaps',
                to='testcases.manualtestcasecategory',
                verbose_name='关联目录',
            ),
        ),
        migrations.RunPython(bind_existing_mindmaps_to_root, migrations.RunPython.noop),
    ]
