# Generated by Django 4.2.7 on 2026-04-17 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_version_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0005_manualtestcasemindmap_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='backend_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backend_mindmaps', to=settings.AUTH_USER_MODEL, verbose_name='后端开发'),
        ),
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='frontend_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_mindmaps', to=settings.AUTH_USER_MODEL, verbose_name='前端开发'),
        ),
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='responsibility_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='责任小组'),
        ),
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_mindmaps', to='versions.version', verbose_name='关联版本'),
        ),
    ]
