# Generated by Django 4.2.7 on 2026-04-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_manualtestcasemindmap_backend_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='关联URL'),
        ),
    ]
