# Generated by Django 4.2.7 on 2026-04-25 07:26

from django.db import migrations, models


def populate_requirement_fields(apps, schema_editor):
    """从脑图名称提取需求编号和标题"""
    ManualTestCaseMindmap = apps.get_model('testcases', 'ManualTestCaseMindmap')
    import re

    pattern = r'(SYSWIN-\d+)\s*(.*)'

    for mindmap in ManualTestCaseMindmap.objects.all():
        if mindmap.name:
            match = re.match(pattern, mindmap.name.strip())
            if match:
                mindmap.requirement_key = match.group(1)
                mindmap.requirement_title = match.group(2).strip()
            else:
                mindmap.requirement_key = ''
                mindmap.requirement_title = ''
        else:
            mindmap.requirement_key = ''
            mindmap.requirement_title = ''

        # 直接更新字段，不触发save信号，避免递归
        ManualTestCaseMindmap.objects.filter(pk=mindmap.pk).update(
            requirement_key=mindmap.requirement_key,
            requirement_title=mindmap.requirement_title
        )


def reverse_populate_requirement_fields(apps, schema_editor):
    """回滚操作：清空需求字段"""
    ManualTestCaseMindmap = apps.get_model('testcases', 'ManualTestCaseMindmap')
    ManualTestCaseMindmap.objects.all().update(requirement_key='', requirement_title='')


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0008_devselftestrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='requirement_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='需求编号'),
        ),
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='requirement_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='需求标题'),
        ),
        migrations.RunPython(populate_requirement_fields, reverse_populate_requirement_fields),
    ]
