# Generated by Django 4.2.7 on 2026-05-07 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0009_add_requirement_fields_to_mindmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaywrightRecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True, verbose_name='Recording session id')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Recording name')),
                ('target_url', models.URLField(max_length=1000, verbose_name='Target URL')),
                ('browser_type', models.CharField(default='chromium', max_length=30, verbose_name='Browser type')),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('recording', 'Recording'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed')], default='starting', max_length=20, verbose_name='Recording status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started at')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Stopped at')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Recording metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playwright_recording_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
            ],
            options={
                'verbose_name': 'Playwright recording session',
                'verbose_name_plural': 'Playwright recording sessions',
                'db_table': 'playwright_recording_sessions',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaywrightRecordingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Step number')),
                ('action_type', models.CharField(max_length=40, verbose_name='Action type')),
                ('action_value', models.TextField(blank=True, verbose_name='Action value')),
                ('page_url', models.TextField(blank=True, verbose_name='Page URL')),
                ('page_title', models.CharField(blank=True, max_length=500, verbose_name='Page title')),
                ('element', models.JSONField(blank=True, default=dict, verbose_name='Element data')),
                ('selectors', models.JSONField(blank=True, default=list, verbose_name='Selector candidates')),
                ('snapshot_filename', models.CharField(blank=True, max_length=255, verbose_name='Snapshot filename')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, verbose_name='Screenshot path')),
                ('raw_event', models.JSONField(blank=True, default=dict, verbose_name='Raw event data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.playwrightrecordingsession', verbose_name='Recording session')),
            ],
            options={
                'verbose_name': 'Playwright recording step',
                'verbose_name_plural': 'Playwright recording steps',
                'db_table': 'playwright_recording_steps',
                'ordering': ['session', 'step_number'],
                'unique_together': {('session', 'step_number')},
            },
        ),
    ]
