# Generated by Django 4.2.7 on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0010_playwrightrecordingsession_playwrightrecordingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=64, unique=True, verbose_name='Visual flow id')),
                ('name', models.CharField(max_length=200, verbose_name='Flow name')),
                ('description', models.TextField(blank=True, verbose_name='Flow description')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('recording', 'Recording')], default='manual', max_length=20, verbose_name='Flow source')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Flow status')),
                ('target_url', models.TextField(blank=True, verbose_name='Target URL')),
                ('browser_type', models.CharField(blank=True, default='chromium', max_length=30, verbose_name='Browser type')),
                ('graph_data', models.JSONField(blank=True, default=dict, verbose_name='X6 graph data')),
                ('snapshot_summary', models.JSONField(blank=True, default=dict, verbose_name='Snapshot summary')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Flow metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_flows', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('recording_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_flows', to='testcases.playwrightrecordingsession', verbose_name='Recording session')),
            ],
            options={
                'verbose_name': 'Visual flow',
                'verbose_name_plural': 'Visual flows',
                'db_table': 'visual_flows',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
