# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0011_visualflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='playwrightrecordingsession',
            name='recording_method',
            field=models.CharField(
                choices=[
                    ('server_playwright_cli', '服务端Playwright CLI录制'),
                    ('local_agent_playwright', '本地Agent- Playwright录制'),
                ],
                default='server_playwright_cli',
                max_length=40,
                verbose_name='Recording method',
            ),
        ),
    ]
