# Generated by Codex on 2026-05-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_executor_from_author(apps, schema_editor):
    ManualTestCaseMindmap = apps.get_model('testcases', 'ManualTestCaseMindmap')
    for mindmap in ManualTestCaseMindmap.objects.filter(executor__isnull=True).only('id', 'author_id'):
        if mindmap.author_id:
            ManualTestCaseMindmap.objects.filter(pk=mindmap.pk).update(executor_id=mindmap.author_id)


def clear_executor(apps, schema_editor):
    ManualTestCaseMindmap = apps.get_model('testcases', 'ManualTestCaseMindmap')
    ManualTestCaseMindmap.objects.all().update(executor_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0012_playwrightrecordingsession_recording_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtestcasemindmap',
            name='executor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='executed_manual_mindmaps',
                to=settings.AUTH_USER_MODEL,
                verbose_name='执行人',
            ),
        ),
        migrations.RunPython(populate_executor_from_author, clear_executor),
    ]
