# Generated by Codex on 2026-05-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0013_manualtestcasemindmap_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualFlowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=64, unique=True, verbose_name='Execution id')),
                ('flow_id_text', models.CharField(blank=True, max_length=64, verbose_name='Flow id text')),
                ('flow_name', models.CharField(blank=True, max_length=200, verbose_name='Flow name')),
                ('run_type', models.CharField(choices=[('backend', 'Backend'), ('local', 'Local')], default='backend', max_length=20, verbose_name='Run type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=20, verbose_name='Status')),
                ('graph_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Graph snapshot')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Execution summary')),
                ('stdout', models.TextField(blank=True, verbose_name='Stdout')),
                ('stderr', models.TextField(blank=True, verbose_name='Stderr')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('returncode', models.IntegerField(blank=True, null=True, verbose_name='Return code')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('duration', models.FloatField(default=0, verbose_name='Duration seconds')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_flow_executions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='testcases.visualflow', verbose_name='Visual flow')),
            ],
            options={
                'verbose_name': 'Visual flow execution',
                'verbose_name_plural': 'Visual flow executions',
                'db_table': 'visual_flow_executions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VisualFlowExecutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=200, verbose_name='Step key')),
                ('step_order', models.PositiveIntegerField(default=0, verbose_name='Step order')),
                ('item_type', models.CharField(choices=[('node', 'Node'), ('component', 'Component')], default='node', max_length=20, verbose_name='Item type')),
                ('node_id', models.CharField(blank=True, max_length=120, verbose_name='Node id')),
                ('component_id', models.CharField(blank=True, max_length=120, verbose_name='Component id')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Title')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='Input data')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='Output data')),
                ('error_log', models.TextField(blank=True, verbose_name='Error log')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, verbose_name='Screenshot path')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('duration', models.FloatField(default=0, verbose_name='Duration seconds')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.visualflowexecution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'Visual flow execution step',
                'verbose_name_plural': 'Visual flow execution steps',
                'db_table': 'visual_flow_execution_steps',
                'ordering': ['execution', 'step_order', 'id'],
                'unique_together': {('execution', 'step_key')},
            },
        ),
    ]
