# Generated by Codex on 2026-05-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import apps.testcases.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('versions', '0001_initial'),
        ('testcases', '0014_visualflowexecution_visualflowexecutionstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaywrightAutomationScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.CharField(default=apps.testcases.models.generate_playwright_automation_script_id, max_length=64, unique=True, verbose_name='Automation script id')),
                ('name', models.CharField(max_length=200, verbose_name='Script name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_url', models.TextField(blank=True, verbose_name='Target URL')),
                ('instruction', models.TextField(blank=True, verbose_name='Natural language instruction')),
                ('script', models.TextField(blank=True, verbose_name='Current Playwright script')),
                ('summary', models.TextField(blank=True, verbose_name='Generation summary')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Generation warnings')),
                ('planned_actions', models.JSONField(blank=True, default=list, verbose_name='Planned actions')),
                ('generation_source', models.CharField(blank=True, max_length=60, verbose_name='Generation source')),
                ('fallback_reason', models.TextField(blank=True, verbose_name='Fallback reason')),
                ('module', models.JSONField(blank=True, default=dict, verbose_name='Module metadata')),
                ('model', models.JSONField(blank=True, default=dict, verbose_name='Model snapshot')),
                ('capability', models.JSONField(blank=True, default=dict, verbose_name='Skill snapshot')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Extra metadata')),
                ('latest_version', models.PositiveIntegerField(default=0, verbose_name='Latest version number')),
                ('module_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Module id')),
                ('module_name', models.CharField(blank=True, max_length=200, verbose_name='Module name')),
                ('module_path', models.TextField(blank=True, verbose_name='Module path')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playwright_automation_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playwright_automation_scripts', to='projects.project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_playwright_automation_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playwright_automation_scripts', to='versions.version', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Playwright automation script',
                'verbose_name_plural': 'Playwright automation scripts',
                'db_table': 'playwright_automation_scripts',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaywrightAutomationScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Version number')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Script name at version')),
                ('target_url', models.TextField(blank=True, verbose_name='Target URL')),
                ('instruction', models.TextField(blank=True, verbose_name='Natural language instruction')),
                ('script_content', models.TextField(blank=True, verbose_name='Playwright script content')),
                ('summary', models.TextField(blank=True, verbose_name='Generation summary')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Generation warnings')),
                ('planned_actions', models.JSONField(blank=True, default=list, verbose_name='Planned actions')),
                ('generation_source', models.CharField(blank=True, max_length=60, verbose_name='Generation source')),
                ('fallback_reason', models.TextField(blank=True, verbose_name='Fallback reason')),
                ('module', models.JSONField(blank=True, default=dict, verbose_name='Module metadata')),
                ('model', models.JSONField(blank=True, default=dict, verbose_name='Model snapshot')),
                ('capability', models.JSONField(blank=True, default=dict, verbose_name='Skill snapshot')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Extra metadata')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='Change summary')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playwright_automation_script_versions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='testcases.playwrightautomationscript', verbose_name='Automation script')),
            ],
            options={
                'verbose_name': 'Playwright automation script version',
                'verbose_name_plural': 'Playwright automation script versions',
                'db_table': 'playwright_automation_script_versions',
                'ordering': ['-version', '-id'],
                'unique_together': {('script', 'version')},
            },
        ),
    ]
