# Generated by Django 4.2.7 on 2026-04-19 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versions', '0002_version_is_default'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='缺陷编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('new', '新缺陷'), ('in_progress', '处理中'), ('resolved', '已解决'), ('rejected', '已拒绝'), ('closed', '已关闭'), ('reopened', '已重新打开'), ('invalid', '作废')], default='new', max_length=20, verbose_name='状态')),
                ('requirement_id', models.CharField(blank=True, max_length=255, verbose_name='需求ID')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_defects', to=settings.AUTH_USER_MODEL, verbose_name='关闭人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_defects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='projects.project', verbose_name='所属项目')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='versions.version', verbose_name='关联版本')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
                'db_table': 'defects',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defect', verbose_name='关联缺陷')),
            ],
            options={
                'verbose_name': '缺陷评论',
                'verbose_name_plural': '缺陷评论',
                'db_table': 'defect_comments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DefectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='附件名称')),
                ('file', models.FileField(upload_to='defect_attachments/%Y/%m/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='defects.defect', verbose_name='关联缺陷')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_defect_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '缺陷附件',
                'verbose_name_plural': '缺陷附件',
                'db_table': 'defect_attachments',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='字段')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('status', '状态变更'), ('assign', '指派'), ('comment', '评论'), ('attachment', '附件')], default='update', max_length=20, verbose_name='动作')),
                ('from_value', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('to_value', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_history_records', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='defects.defect', verbose_name='关联缺陷')),
            ],
            options={
                'verbose_name': '缺陷变更记录',
                'verbose_name_plural': '缺陷变更记录',
                'db_table': 'defect_histories',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['defect'], name='defect_hist_defect__637180_idx'), models.Index(fields=['action'], name='defect_hist_action_2d4aa4_idx'), models.Index(fields=['created_at'], name='defect_hist_created_3bb8fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['code'], name='defects_code_f2d8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['project'], name='defects_project_eb2df5_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['version'], name='defects_version_2e45fb_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['severity'], name='defects_severit_e0064a_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['status'], name='defects_status_734a01_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['created_at'], name='defects_created_499878_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['updated_at'], name='defects_updated_9ec99a_idx'),
        ),
    ]
