# Generated by Django 4.2.7 on 2026-04-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='modules',
            field=models.JSONField(blank=True, default=list, verbose_name='关联模块'),
        ),
        migrations.AddField(
            model_name='defect',
            name='related_testcases',
            field=models.JSONField(blank=True, default=list, verbose_name='关联测试用例'),
        ),
        migrations.AddField(
            model_name='defect',
            name='related_testpoints',
            field=models.JSONField(blank=True, default=list, verbose_name='关联测试点'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='requirement_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='JIRA编号'),
        ),
    ]
