# Generated by Django 4.2.7 on 2026-04-20 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defects', '0002_defect_modules_defect_related_testcases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP服务器')),
                ('port', models.PositiveIntegerField(default=465, verbose_name='SMTP端口')),
                ('username', models.CharField(max_length=255, verbose_name='SMTP用户名')),
                ('password', models.CharField(max_length=255, verbose_name='SMTP密码或授权码')),
                ('from_name', models.CharField(default='缺陷管理平台', max_length=255, verbose_name='发件人名称')),
                ('from_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('new_bug_template', models.TextField(blank=True, verbose_name='新缺陷邮件模板')),
                ('resolved_bug_template', models.TextField(blank=True, verbose_name='已解决邮件模板')),
                ('rejected_bug_template', models.TextField(blank=True, verbose_name='已拒绝邮件模板')),
                ('reopened_bug_template', models.TextField(blank=True, verbose_name='重新打开邮件模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_defect_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_defect_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '缺陷邮件配置',
                'verbose_name_plural': '缺陷邮件配置',
                'db_table': 'defect_email_configs',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='defectemailconfig',
            index=models.Index(fields=['is_active'], name='defect_emai_is_acti_f09177_idx'),
        ),
        migrations.AddIndex(
            model_name='defectemailconfig',
            index=models.Index(fields=['updated_at'], name='defect_emai_updated_db9c98_idx'),
        ),
    ]
