# Generated by Django 4.2.7 on 2026-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_seed_default_email_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='problem_reason',
            field=models.TextField(blank=True, default='', verbose_name='问题原因'),
        ),
        migrations.AddField(
            model_name='defect',
            name='root_cause',
            field=models.TextField(blank=True, default='', verbose_name='问题根因'),
        ),
    ]
