# Generated by Django 4.2.7 on 2026-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_defect_problem_reason_defect_root_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P3', max_length=2, verbose_name='优先级'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['priority'], name='defects_priorit_04277e_idx'),
        ),
    ]
