# Generated by Django 4.2.7 on 2026-05-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_project_status'),
        ('defects', '0009_rename_defects_record_type_idx_defects_record__515d54_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='record_type',
            field=models.CharField(choices=[('defect', '缺陷'), ('technical_solution_design', '技术方案设计'), ('wiki', 'Wiki')], default='defect', max_length=40, verbose_name='记录类型'),
        ),
        migrations.CreateModel(
            name='WikiDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目录名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='目录描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wiki_directories', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='defects.wikidirectory', verbose_name='父级目录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_directories', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Wiki目录',
                'verbose_name_plural': 'Wiki目录',
                'db_table': 'wiki_directories',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['project', 'parent'], name='wiki_direct_project_47861b_idx'), models.Index(fields=['project', 'name'], name='wiki_direct_project_dd28fe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wikidirectory',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='uniq_wiki_directory_sibling_name'),
        ),
    ]
