# Generated by Django 4.2.7 on 2026-06-19 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_projectenvironment_credentials_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Space Key')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('space_type', models.CharField(choices=[('platform', 'Platform'), ('module', 'Module'), ('project', 'Project'), ('repository', 'Repository'), ('system', 'System')], default='project', max_length=32, verbose_name='Space Type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_knowledge_spaces', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_spaces', to='projects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'knowledge_spaces',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRepositoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('provider', models.CharField(choices=[('local', 'Local'), ('git', 'Git'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee')], default='local', max_length=32, verbose_name='Provider')),
                ('repository_mode', models.CharField(choices=[('remote', 'Remote Repository'), ('local_path', 'Local Path Repository')], default='local_path', max_length=20, verbose_name='Repository Mode')),
                ('auth_mode', models.CharField(choices=[('none', 'None'), ('token', 'Token'), ('ssh', 'SSH'), ('oauth', 'OAuth'), ('github_app', 'GitHub App')], default='none', max_length=32, verbose_name='Auth Mode')),
                ('repository_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Repository URL')),
                ('local_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Local Repository Path')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='Username')),
                ('access_token_encrypted', models.CharField(blank=True, default='', max_length=1000, verbose_name='Encrypted Access Token')),
                ('ssh_key_encrypted', models.TextField(blank=True, default='', verbose_name='Encrypted SSH Key')),
                ('default_branch', models.CharField(default='main', max_length=100, verbose_name='Default Branch')),
                ('index_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Index Ref')),
                ('code_root', models.CharField(blank=True, default='.', max_length=255, verbose_name='Code Root')),
                ('frontend_root', models.CharField(blank=True, default='frontend', max_length=255, verbose_name='Frontend Root')),
                ('backend_root', models.CharField(blank=True, default='apps', max_length=255, verbose_name='Backend Root')),
                ('docs_root', models.CharField(blank=True, default='docs', max_length=255, verbose_name='Docs Root')),
                ('include_patterns', models.JSONField(blank=True, default=list, verbose_name='Include Patterns')),
                ('exclude_patterns', models.JSONField(blank=True, default=list, verbose_name='Exclude Patterns')),
                ('authorization_status', models.CharField(choices=[('not_configured', 'Not Configured'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('failed', 'Failed')], default='not_configured', max_length=32, verbose_name='Authorization Status')),
                ('authorization_state', models.CharField(blank=True, default='', max_length=128, verbose_name='Authorization State')),
                ('authorization_scopes', models.JSONField(blank=True, default=list, verbose_name='Authorization Scopes')),
                ('authorization_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Authorization Message')),
                ('last_test_result', models.JSONField(blank=True, default=dict, verbose_name='Last Test Result')),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Indexed At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_repository_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_repository_configs', to='projects.project', verbose_name='Project')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_configs', to='knowledge.knowledgespace', verbose_name='Knowledge Space')),
            ],
            options={
                'db_table': 'knowledge_repository_configs',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQueryTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('normalized_query', models.TextField(blank=True, default='', verbose_name='Normalized Query')),
                ('matched_objects', models.JSONField(blank=True, default=list, verbose_name='Matched Objects')),
                ('evidence_nodes', models.JSONField(blank=True, default=list, verbose_name='Evidence Nodes')),
                ('evidence_edges', models.JSONField(blank=True, default=list, verbose_name='Evidence Edges')),
                ('roadmap_paths', models.JSONField(blank=True, default=list, verbose_name='Roadmap Paths')),
                ('data_sources', models.JSONField(blank=True, default=list, verbose_name='Data Sources')),
                ('context_payload', models.JSONField(blank=True, default=dict, verbose_name='Context Payload')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Confidence Score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_query_traces', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_query_traces', to='projects.project', verbose_name='Project')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_traces', to='knowledge.knowledgespace', verbose_name='Knowledge Space')),
            ],
            options={
                'db_table': 'knowledge_query_traces',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('platform', 'Platform'), ('module', 'Module'), ('menu', 'Menu'), ('page', 'Page'), ('tab', 'Tab'), ('function', 'Function'), ('operation', 'Operation'), ('field', 'Field'), ('api', 'API'), ('database', 'Database'), ('table', 'Table'), ('component', 'Component'), ('route', 'Route'), ('repository', 'Repository'), ('document', 'Document'), ('business_data', 'Business Data')], max_length=32, verbose_name='Object Type')),
                ('key', models.CharField(max_length=255, verbose_name='Object Key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Summary')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('roadmap_path', models.JSONField(blank=True, default=list, verbose_name='Roadmap Path')),
                ('page_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Page Path')),
                ('tab_key', models.CharField(blank=True, default='', max_length=100, verbose_name='Tab Key')),
                ('component_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Component Path')),
                ('api_path', models.CharField(blank=True, default='', max_length=500, verbose_name='API Path')),
                ('db_table', models.CharField(blank=True, default='', max_length=200, verbose_name='Database Table')),
                ('field_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Field Name')),
                ('source_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Source Type')),
                ('source_ref', models.CharField(blank=True, default='', max_length=500, verbose_name='Source Reference')),
                ('source_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Source Hash')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('search_text', models.TextField(blank=True, default='', verbose_name='Search Text')),
                ('indexed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Indexed At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_objects', to='projects.project', verbose_name='Project')),
                ('repository_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='knowledge.knowledgerepositoryconfig', verbose_name='Repository Config')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_objects', to='knowledge.knowledgespace', verbose_name='Knowledge Space')),
            ],
            options={
                'db_table': 'knowledge_objects',
                'ordering': ['object_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIndexRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=32, verbose_name='Status')),
                ('trigger', models.CharField(blank=True, default='manual', max_length=64, verbose_name='Trigger')),
                ('index_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Index Ref')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('object_count', models.PositiveIntegerField(default=0, verbose_name='Object Count')),
                ('relation_count', models.PositiveIntegerField(default=0, verbose_name='Relation Count')),
                ('changed_object_count', models.PositiveIntegerField(default=0, verbose_name='Changed Object Count')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='Report')),
                ('log', models.TextField(blank=True, default='', verbose_name='Log')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_index_runs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('repository_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_runs', to='knowledge.knowledgerepositoryconfig', verbose_name='Repository Config')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_runs', to='knowledge.knowledgespace', verbose_name='Knowledge Space')),
            ],
            options={
                'db_table': 'knowledge_index_runs',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correction', 'Correction'), ('confirmation', 'Confirmation'), ('supplement', 'Supplement')], default='correction', max_length=32, verbose_name='Feedback Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('status', models.CharField(default='open', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_feedback_items', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('knowledge_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='knowledge.knowledgeobject', verbose_name='Knowledge Object')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='knowledge.knowledgequerytrace', verbose_name='Query Trace')),
            ],
            options={
                'db_table': 'knowledge_feedback',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('contains', 'Contains'), ('belongs_to', 'Belongs To'), ('opens', 'Opens'), ('implements', 'Implements'), ('calls', 'Calls'), ('reads', 'Reads'), ('writes', 'Writes'), ('uses', 'Uses'), ('same_as', 'Same As'), ('related_to', 'Related To')], max_length=32, verbose_name='Relation Type')),
                ('label', models.CharField(blank=True, default='', max_length=150, verbose_name='Label')),
                ('weight', models.FloatField(default=1.0, verbose_name='Weight')),
                ('source_ref', models.CharField(blank=True, default='', max_length=500, verbose_name='Source Reference')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge.knowledgeobject', verbose_name='Source Object')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='knowledge.knowledgespace', verbose_name='Knowledge Space')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge.knowledgeobject', verbose_name='Target Object')),
            ],
            options={
                'db_table': 'knowledge_relations',
                'ordering': ['source_id', 'target_id', 'relation_type'],
                'indexes': [models.Index(fields=['space', 'relation_type'], name='knowledge_rel_space_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.UniqueConstraint(fields=('space', 'source', 'target', 'relation_type'), name='knowledge_rel_space_edge_unique'),
        ),
        migrations.AddIndex(
            model_name='knowledgeobject',
            index=models.Index(fields=['space', 'object_type'], name='knowledge_obj_space_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeobject',
            index=models.Index(fields=['project', 'object_type'], name='knowledge_obj_project_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeobject',
            index=models.Index(fields=['tab_key'], name='knowledge_obj_tab_key_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeobject',
            index=models.Index(fields=['db_table'], name='knowledge_obj_db_table_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeobject',
            constraint=models.UniqueConstraint(fields=('space', 'key'), name='knowledge_objects_space_key_unique'),
        ),
    ]
