# Generated by Django 4.2.7 on 2026-04-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否为默认版本'),
        ),
    ]
