from django.db import migrations


MANUAL_TESTCASE_PERMISSION_ITEMS = [
    {
        'code': 'module:manual-testcases',
        'name': '思源研发管理',
        'item_type': 'module',
        'sort_order': 70,
    },
    {
        'code': 'menu:manual-testcases:list',
        'name': '思源研发管理',
        'item_type': 'menu',
        'parent_code': 'module:manual-testcases',
        'sort_order': 10,
        'route_path': '/manual-testcases/list',
    },
    {
        'code': 'menu:manual-testcases:product',
        'name': '需求',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=version-requirements',
    },
    {
        'code': 'menu:manual-testcases:version-requirements',
        'name': '版本需求',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:product',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=version-requirements',
    },
    {
        'code': 'button:manual-testcases:version-requirements:create',
        'name': '新增需求',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:version-requirements',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:version-requirements:edit',
        'name': '编辑需求',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:version-requirements',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:version-requirements:delete',
        'name': '删除需求',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:version-requirements',
        'sort_order': 30,
    },
    {
        'code': 'action:manual-testcases:version-requirements:view-detail',
        'name': '查看需求详情',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-requirements',
        'sort_order': 40,
    },
    {
        'code': 'action:manual-testcases:version-requirements:jump-mindmaps',
        'name': '打开测试脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-requirements',
        'sort_order': 50,
    },
    {
        'code': 'action:manual-testcases:version-requirements:jump-defects',
        'name': '打开版本缺陷',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-requirements',
        'sort_order': 60,
    },
    {
        'code': 'menu:manual-testcases:requirement-records',
        'name': 'JIRA需求数据',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:product',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=requirement-records',
    },
    {
        'code': 'action:manual-testcases:requirement-records:view-detail',
        'name': '查看需求详情',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:requirement-records',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:requirement-records:jump-mindmaps',
        'name': '打开测试脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:requirement-records',
        'sort_order': 20,
    },
    {
        'code': 'action:manual-testcases:requirement-records:jump-defects',
        'name': '打开版本缺陷',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:requirement-records',
        'sort_order': 30,
    },
    {
        'code': 'menu:manual-testcases:development',
        'name': '开发',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=devselftest',
    },
    {
        'code': 'menu:manual-testcases:devselftest',
        'name': '自测测试点',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:development',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=devselftest',
    },
    {
        'code': 'action:manual-testcases:devselftest:audit',
        'name': '审核自测测试点',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:devselftest',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:devselftest:edit',
        'name': '编辑自测测试点',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:devselftest',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:devselftest:create-defect',
        'name': '提缺陷',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:devselftest',
        'sort_order': 30,
    },
    {
        'code': 'menu:manual-testcases:testing',
        'name': '测试',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 30,
        'route_path': '/manual-testcases/list?tab=mindmaps',
    },
    {
        'code': 'menu:manual-testcases:mindmaps',
        'name': '测试脑图',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:testing',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=mindmaps',
    },
    {
        'code': 'button:manual-testcases:mindmaps:create',
        'name': '新建脑图',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:mindmaps',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:mindmaps:batch-delete',
        'name': '批量删除脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:mindmaps',
        'sort_order': 20,
    },
    {
        'code': 'action:manual-testcases:mindmaps:edit-content',
        'name': '编辑脑图内容',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:mindmaps',
        'sort_order': 30,
    },
    {
        'code': 'action:manual-testcases:mindmaps:view',
        'name': '查看脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:mindmaps',
        'sort_order': 40,
    },
    {
        'code': 'button:manual-testcases:mindmaps:edit',
        'name': '编辑脑图信息',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:mindmaps',
        'sort_order': 50,
    },
    {
        'code': 'button:manual-testcases:mindmaps:delete',
        'name': '删除脑图',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:mindmaps',
        'sort_order': 60,
    },
    {
        'code': 'menu:manual-testcases:testcases',
        'name': '测试用例',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:testing',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=testcases',
    },
    {
        'code': 'action:manual-testcases:testcases:edit-mindmap',
        'name': '编辑脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:testcases',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:testcases:view-mindmap',
        'name': '查看脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:testcases',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:testcases:create-defect',
        'name': '提缺陷',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:testcases',
        'sort_order': 30,
    },
    {
        'code': 'menu:manual-testcases:testpoints',
        'name': '测试点',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:testing',
        'sort_order': 30,
        'route_path': '/manual-testcases/list?tab=testpoints',
    },
    {
        'code': 'action:manual-testcases:testpoints:edit-mindmap',
        'name': '编辑脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:testpoints',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:testpoints:view-mindmap',
        'name': '查看脑图',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:testpoints',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:testpoints:create-defect',
        'name': '提缺陷',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:testpoints',
        'sort_order': 30,
    },
    {
        'code': 'menu:manual-testcases:defect',
        'name': '缺陷',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 40,
        'route_path': '/manual-testcases/list?tab=version-defects',
    },
    {
        'code': 'menu:manual-testcases:version-defects',
        'name': '版本缺陷',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:defect',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=version-defects',
    },
    {
        'code': 'button:manual-testcases:version-defects:create',
        'name': '新建缺陷',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:version-defects:view',
        'name': '查看缺陷',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:version-defects:edit',
        'name': '编辑缺陷',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 30,
    },
    {
        'code': 'button:manual-testcases:version-defects:delete',
        'name': '删除缺陷',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 40,
    },
    {
        'code': 'action:manual-testcases:version-defects:jump-requirement',
        'name': '跳转JIRA需求',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 50,
    },
    {
        'code': 'action:manual-testcases:version-defects:jump-module',
        'name': '跳转关联模块',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 60,
    },
    {
        'code': 'action:manual-testcases:version-defects:jump-case',
        'name': '跳转关联测试用例',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 70,
    },
    {
        'code': 'action:manual-testcases:version-defects:jump-testpoint',
        'name': '跳转关联测试点',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:version-defects',
        'sort_order': 80,
    },
    {
        'code': 'menu:manual-testcases:bug-records',
        'name': '线上缺陷',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:defect',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=bug-records',
    },
    {
        'code': 'action:manual-testcases:bug-records:associate',
        'name': '关联缺陷',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:bug-records',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:bug-records:view-detail',
        'name': '查看缺陷详情',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:bug-records',
        'sort_order': 20,
    },
    {
        'code': 'menu:manual-testcases:reports',
        'name': '报告',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 50,
        'route_path': '/manual-testcases/list?tab=quality-report-list',
    },
    {
        'code': 'menu:manual-testcases:quality-report-list',
        'name': '报告列表',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:reports',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=quality-report-list',
    },
    {
        'code': 'menu:manual-testcases:quality-report-live',
        'name': '实时质量分析',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:reports',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=quality-report-live',
    },
    {
        'code': 'menu:manual-testcases:quality-report-excel',
        'name': 'Excel专项图表',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:reports',
        'sort_order': 30,
        'route_path': '/manual-testcases/list?tab=quality-report-excel',
    },
    {
        'code': 'menu:manual-testcases:config',
        'name': '配置',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 60,
        'route_path': '/manual-testcases/list?tab=configs',
    },
    {
        'code': 'menu:manual-testcases:configs',
        'name': 'JIRA接口配置',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:config',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=configs',
    },
    {
        'code': 'button:manual-testcases:configs:create',
        'name': '新增配置',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:configs',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:configs:edit',
        'name': '编辑配置',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:configs',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:configs:delete',
        'name': '删除配置',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:configs',
        'sort_order': 30,
    },
    {
        'code': 'action:manual-testcases:configs:execute',
        'name': '执行配置',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:configs',
        'sort_order': 40,
    },
    {
        'code': 'menu:manual-testcases:other-settings',
        'name': 'JIRA编号URL前缀配置',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:config',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=other-settings',
    },
    {
        'code': 'action:manual-testcases:other-settings:save',
        'name': '保存配置',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:other-settings',
        'sort_order': 10,
    },
    {
        'code': 'menu:manual-testcases:defect-notifications',
        'name': '缺陷通知',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:config',
        'sort_order': 30,
        'route_path': '/manual-testcases/list?tab=defect-notifications',
    },
    {
        'code': 'menu:manual-testcases:defect-notifications:email-config',
        'name': '邮件配置',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:defect-notifications',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=defect-notifications',
    },
    {
        'code': 'action:manual-testcases:defect-notifications:verify-smtp',
        'name': '校验SMTP',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:defect-notifications:email-config',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:defect-notifications:save-email-config',
        'name': '保存邮件配置',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:defect-notifications:email-config',
        'sort_order': 20,
    },
    {
        'code': 'menu:manual-testcases:defect-notifications:test-email',
        'name': '测试邮件',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:defect-notifications',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=defect-notifications',
    },
    {
        'code': 'action:manual-testcases:defect-notifications:send-test-email',
        'name': '发送测试邮件',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:defect-notifications:test-email',
        'sort_order': 10,
    },
    {
        'code': 'menu:manual-testcases:defect-notifications:notification-settings',
        'name': '消息提醒',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:defect-notifications',
        'sort_order': 30,
        'route_path': '/manual-testcases/list?tab=defect-notifications',
    },
    {
        'code': 'action:manual-testcases:defect-notifications:request-browser-permission',
        'name': '申请浏览器通知权限',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:defect-notifications:notification-settings',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:defect-notifications:save-notification-settings',
        'name': '保存提醒设置',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:defect-notifications:notification-settings',
        'sort_order': 20,
    },
    {
        'code': 'menu:manual-testcases:management',
        'name': '管理',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:list',
        'sort_order': 70,
        'route_path': '/manual-testcases/list?tab=members',
    },
    {
        'code': 'menu:manual-testcases:members',
        'name': '成员',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:management',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=members',
    },
    {
        'code': 'button:manual-testcases:members:create',
        'name': '新增成员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:members',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:members:edit',
        'name': '编辑成员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:members',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:members:delete',
        'name': '删除成员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:members',
        'sort_order': 30,
    },
    {
        'code': 'menu:manual-testcases:groups',
        'name': '组别',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:management',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=groups',
    },
    {
        'code': 'button:manual-testcases:groups:create',
        'name': '新增组别',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:groups',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:groups:edit',
        'name': '编辑组别',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:groups',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:groups:delete',
        'name': '删除组别',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:groups',
        'sort_order': 30,
    },
    {
        'code': 'button:manual-testcases:groups:members:create',
        'name': '新增组员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:groups',
        'sort_order': 40,
    },
    {
        'code': 'button:manual-testcases:groups:members:edit',
        'name': '编辑组员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:groups',
        'sort_order': 50,
    },
    {
        'code': 'button:manual-testcases:groups:members:delete',
        'name': '删除组员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:groups',
        'sort_order': 60,
    },
    {
        'code': 'menu:manual-testcases:roles',
        'name': '角色',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:management',
        'sort_order': 30,
        'route_path': '/manual-testcases/list?tab=roles',
    },
    {
        'code': 'button:manual-testcases:roles:create',
        'name': '新增角色',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:roles',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:roles:edit',
        'name': '编辑角色',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:roles',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:roles:delete',
        'name': '删除角色',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:roles',
        'sort_order': 30,
    },
    {
        'code': 'button:manual-testcases:roles:members:create',
        'name': '新增角色成员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:roles',
        'sort_order': 40,
    },
    {
        'code': 'button:manual-testcases:roles:members:edit',
        'name': '编辑角色成员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:roles',
        'sort_order': 50,
    },
    {
        'code': 'button:manual-testcases:roles:members:delete',
        'name': '删除角色成员',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:roles',
        'sort_order': 60,
    },
    {
        'code': 'menu:manual-testcases:permissions',
        'name': '权限',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:management',
        'sort_order': 40,
        'route_path': '/manual-testcases/list?tab=permissions',
    },
    {
        'code': 'menu:manual-testcases:permissions:ui-role-permissions',
        'name': 'UI角色权限',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:permissions',
        'sort_order': 10,
        'route_path': '/manual-testcases/list?tab=permissions',
    },
    {
        'code': 'action:manual-testcases:permissions:assign',
        'name': '分配角色权限',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:permissions:ui-role-permissions',
        'sort_order': 10,
    },
    {
        'code': 'action:manual-testcases:permissions:view',
        'name': '查看权限树',
        'item_type': 'action',
        'parent_code': 'menu:manual-testcases:permissions:ui-role-permissions',
        'sort_order': 20,
    },
    {
        'code': 'menu:manual-testcases:permissions:permission-catalog',
        'name': '权限目录',
        'item_type': 'menu',
        'parent_code': 'menu:manual-testcases:permissions',
        'sort_order': 20,
        'route_path': '/manual-testcases/list?tab=permissions',
    },
    {
        'code': 'button:manual-testcases:permissions:create',
        'name': '新增权限项',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:permissions:permission-catalog',
        'sort_order': 10,
    },
    {
        'code': 'button:manual-testcases:permissions:edit',
        'name': '编辑权限项',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:permissions:permission-catalog',
        'sort_order': 20,
    },
    {
        'code': 'button:manual-testcases:permissions:delete',
        'name': '删除权限项',
        'item_type': 'button',
        'parent_code': 'menu:manual-testcases:permissions:permission-catalog',
        'sort_order': 30,
    },
    {
        'code': 'menu:manual-testcases:snapshots',
        'name': '快照文件管理',
        'item_type': 'menu',
        'parent_code': 'module:manual-testcases',
        'sort_order': 20,
        'route_path': '/manual-testcases/snapshots',
    },
    {
        'code': 'menu:manual-testcases:visual-flow',
        'name': '可视化流程编辑器',
        'item_type': 'menu',
        'parent_code': 'module:manual-testcases',
        'sort_order': 30,
        'route_path': '/manual-testcases/visual-flow',
    },
    {
        'code': 'menu:manual-testcases:workflow-workbench',
        'name': '流程工作台',
        'item_type': 'menu',
        'parent_code': 'module:manual-testcases',
        'sort_order': 40,
        'route_path': '/manual-testcases/workflow-workbench',
    },
]


def sync_manual_testcase_permission_items(apps, schema_editor):
    PermissionItem = apps.get_model('users', 'PermissionItem')
    item_mapping = {}

    for item in MANUAL_TESTCASE_PERMISSION_ITEMS:
        defaults = {
            'name': item['name'],
            'item_type': item['item_type'],
            'route_path': item.get('route_path', ''),
            'sort_order': item.get('sort_order', 0),
            'is_active': item.get('is_active', True),
            'description': item.get('description', ''),
        }
        permission_item, _ = PermissionItem.objects.update_or_create(
            code=item['code'],
            defaults=defaults,
        )
        item_mapping[item['code']] = permission_item

    for item in MANUAL_TESTCASE_PERMISSION_ITEMS:
        permission_item = item_mapping[item['code']]
        parent_code = item.get('parent_code')
        parent_item = item_mapping.get(parent_code) if parent_code else None
        parent_id = parent_item.id if parent_item else None
        if permission_item.parent_id != parent_id:
            permission_item.parent_id = parent_id
            permission_item.save(update_fields=['parent'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_permissionitem_rolepermission'),
    ]

    operations = [
        migrations.RunPython(sync_manual_testcase_permission_items, migrations.RunPython.noop),
    ]
