# Generated by Django 4.2.7 on 2026-04-21 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_type', models.CharField(choices=[('defect', 'Defect'), ('requirement', 'Requirement')], max_length=32)),
                ('key', models.CharField(max_length=100)),
                ('scene_key', models.CharField(default='default', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_definitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['biz_type', 'key', '-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_type', models.CharField(choices=[('defect', 'Defect'), ('requirement', 'Requirement')], max_length=32)),
                ('biz_id', models.PositiveIntegerField()),
                ('biz_code', models.CharField(blank=True, max_length=100)),
                ('biz_title', models.CharField(blank=True, max_length=255)),
                ('business_key', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='running', max_length=20)),
                ('current_step_key', models.CharField(blank=True, max_length=100)),
                ('current_step_name', models.CharField(blank=True, max_length=200)),
                ('current_task_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scene_key', models.CharField(default='default', max_length=100)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances_assigned', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_instances',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=100)),
                ('step_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('candidate_groups', models.JSONField(blank=True, default=list)),
                ('available_actions', models.JSONField(blank=True, default=list)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_due_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('candidate_users', models.ManyToManyField(blank=True, related_name='workflow_tasks_candidate', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_tasks',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_type', models.CharField(choices=[('defect', 'Defect'), ('requirement', 'Requirement')], max_length=32)),
                ('scene_key', models.CharField(default='default', max_length=100)),
                ('step_key', models.CharField(default='*', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_rules',
                'ordering': ['biz_type', 'scene_key', 'step_key', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_type', models.CharField(choices=[('defect', 'Defect'), ('requirement', 'Requirement')], max_length=32)),
                ('biz_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('from_step_key', models.CharField(blank=True, max_length=100)),
                ('from_step_name', models.CharField(blank=True, max_length=200)),
                ('to_step_key', models.CharField(blank=True, max_length=100)),
                ('to_step_name', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.workflowinstance')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_action_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='workflow.workflowtask')),
            ],
            options={
                'db_table': 'workflow_action_logs',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['status'], name='workflow_ta_status_9b2394_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['step_key'], name='workflow_ta_step_ke_668e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['due_at'], name='workflow_ta_due_at_fdfe55_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['biz_type', 'biz_id'], name='workflow_in_biz_typ_1a4092_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status'], name='workflow_in_status_a4291a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['current_step_key'], name='workflow_in_current_42f37f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('biz_type', 'key', 'version')},
        ),
        migrations.AddIndex(
            model_name='workflowactionlog',
            index=models.Index(fields=['biz_type', 'biz_id'], name='workflow_ac_biz_typ_fa58be_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowactionlog',
            index=models.Index(fields=['action'], name='workflow_ac_action_b2d486_idx'),
        ),
    ]
