# Generated by Django 4.2.7 on 2026-04-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowinstance_run_number_and_multi_start'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_biz_typ_620ef3_idx',
            old_name='workflow_in_biz_run_5df38f_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_busines_41e7aa_idx',
            old_name='workflow_in_busines_bdb688_idx',
        ),
    ]
