# Generated by Django 4.2.7 on 2026-04-18 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True, verbose_name='版本号')),
                ('source_excel', models.FileField(upload_to='quality-analysis/source/%Y/%m/', verbose_name='缺陷数据 Excel')),
                ('processed_excel', models.FileField(blank=True, null=True, upload_to='quality-analysis/processed/%Y/%m/', verbose_name='处理后的缺陷 Excel')),
                ('requirement_excel', models.FileField(blank=True, null=True, upload_to='quality-analysis/requirements/%Y/%m/', verbose_name='需求清单 Excel')),
                ('testcase_excel', models.FileField(blank=True, null=True, upload_to='quality-analysis/testcases/%Y/%m/', verbose_name='测试用例统计 Excel')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('analyzing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('total_defects', models.PositiveIntegerField(default=0, verbose_name='缺陷总数')),
                ('classified_defects', models.PositiveIntegerField(default=0, verbose_name='已分类缺陷数')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='分析结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('share_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='分享令牌')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '质量分析报告',
                'verbose_name_plural': '质量分析报告',
                'db_table': 'quality_analysis_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
