# Generated by Django 4.2.7 on 2026-04-18 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality_analysis', '0002_jirainterfaceconfig_jirabugrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraRequirementInterfaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True, verbose_name='版本号')),
                ('name', models.CharField(default='JIRA需求接口', max_length=100, verbose_name='配置名称')),
                ('request_url', models.CharField(max_length=500, verbose_name='请求 URL')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10, verbose_name='请求方法')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, verbose_name='请求体')),
                ('timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='超时时间(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='最后响应状态码')),
                ('last_record_count', models.PositiveIntegerField(default=0, verbose_name='最后同步记录数')),
                ('last_execution_message', models.TextField(blank=True, verbose_name='最后执行结果')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_requirement_interface_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'JIRA需求接口配置',
                'verbose_name_plural': 'JIRA需求接口配置',
                'db_table': 'quality_analysis_jira_requirement_configs',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JiraRequirementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=100, verbose_name='版本号')),
                ('issue_id', models.CharField(blank=True, max_length=50, verbose_name='JIRA内部ID')),
                ('issue_key', models.CharField(db_index=True, max_length=100, verbose_name='问题编号')),
                ('issue_type', models.CharField(blank=True, max_length=100, verbose_name='问题类型')),
                ('summary', models.TextField(blank=True, verbose_name='标题')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='客户名称')),
                ('priority', models.CharField(blank=True, max_length=100, verbose_name='优先级')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='状态')),
                ('creator', models.CharField(blank=True, max_length=100, verbose_name='创建人')),
                ('handler', models.CharField(blank=True, max_length=100, verbose_name='处理人')),
                ('tester', models.CharField(blank=True, max_length=100, verbose_name='测试人员')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='责任组')),
                ('row_index', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('raw_fields', models.JSONField(blank=True, default=dict, verbose_name='原始字段')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_records', to='quality_analysis.jirarequirementinterfaceconfig', verbose_name='来源配置')),
            ],
            options={
                'verbose_name': 'JIRA需求数据',
                'verbose_name_plural': 'JIRA需求数据',
                'db_table': 'quality_analysis_jira_requirement_records',
                'ordering': ['-synced_at', 'row_index', 'issue_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='jirarequirementrecord',
            constraint=models.UniqueConstraint(fields=('version', 'issue_key'), name='uq_quality_analysis_jira_requirement_version_key'),
        ),
    ]
