# Generated by Django 4.2.7 on 2026-04-18 06:18

from urllib.parse import urlencode

from django.db import migrations


DEFAULT_VERSION = '26-04.15发版（8.2.0）'


def seed_jira_requirement_config(apps, schema_editor):
    JiraRequirementInterfaceConfig = apps.get_model('quality_analysis', 'JiraRequirementInterfaceConfig')

    headers = {
        '__amdmodulename': 'jira/issue/utils/xsrf-token-header',
        'accept': '*/*',
        'accept-encoding': 'gzip, deflate',
        'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
        'connection': 'keep-alive',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'cookie': (
            'seraph.rememberme.cookie=21537%3Af94e4b6896599b9e0fab7a3a0b3d86d765ef4e0a; '
            'atlassian.xsrf.token=BYAD-0586-UEY0-GUQV|ac2d3e63651efedad8852ca6cd3069a649039c55|lin; '
            'JSESSIONID=3F4093AC153C08047C70416F21B0EEB2'
        ),
        'origin': 'http://172.31.119.34:8080',
        'referer': 'http://172.31.119.34:8080/issues/?filter=15943',
        'user-agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
            '(KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36 Edg/147.0.0.0'
        ),
        'x-atlassian-token': 'no-check',
        'x-requested-with': 'XMLHttpRequest',
    }
    body = urlencode(
        {
            'startIndex': 0,
            'filterId': 15943,
            'jql': (
                'project = SYSWIN AND issuetype in (任务, 实施需求（二次开发）, 实施需求（合同内）, '
                '标准化需求, 子任务-需求分拆) AND status in '
                '(产品需求待接收, 产品规划设计中, 产品设计完成, 待启动研发任务, 功能研发中, 研发技术评审, '
                '代码开发完成, 功能测试中, 测试完成待发版, 开发任务完结, 需求报告人验收中, 已交付上线, '
                f'已关闭问题, 已挂起问题) AND fixVersion = {DEFAULT_VERSION} '
                'ORDER BY cf[10761] DESC, cf[10747] DESC, cf[10741] ASC, key ASC, '
                'cf[10762] DESC, reporter ASC, assignee ASC, cf[10708] ASC, '
                'issuetype DESC, cf[10738] DESC'
            ),
            'layoutKey': 'list-view',
        }
    )

    JiraRequirementInterfaceConfig.objects.update_or_create(
        version=DEFAULT_VERSION,
        defaults={
            'name': 'JIRA需求接口',
            'request_url': 'http://172.31.119.34:8080/rest/issueNav/1/issueTable',
            'request_method': 'POST',
            'request_headers': headers,
            'request_body': body,
            'timeout_seconds': 60,
            'is_active': True,
            'notes': '系统预置的 JIRA 需求接口配置',
        },
    )


def reverse_seed_jira_requirement_config(apps, schema_editor):
    JiraRequirementInterfaceConfig = apps.get_model('quality_analysis', 'JiraRequirementInterfaceConfig')
    JiraRequirementInterfaceConfig.objects.filter(version=DEFAULT_VERSION, name='JIRA需求接口').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quality_analysis', '0003_jirarequirementinterfaceconfig_jirarequirementrecord_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_jira_requirement_config, reverse_seed_jira_requirement_config),
    ]
