# Generated by Django 4.2.7 on 2026-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_analysis', '0009_jirabugrecord_associations'),
    ]

    operations = []
