# Generated by Django 4.2.7 on 2026-04-24 04:48

from django.db import migrations, models
import django.utils.timezone


DEFAULT_JIRA_BROWSE_PREFIX = 'http://172.31.119.34:8080/browse/'


def seed_quality_analysis_settings(apps, schema_editor):
    QualityAnalysisSettings = apps.get_model('quality_analysis', 'QualityAnalysisSettings')
    if QualityAnalysisSettings.objects.exists():
        return
    QualityAnalysisSettings.objects.create(
        singleton_key='default',
        jira_browse_prefix=DEFAULT_JIRA_BROWSE_PREFIX,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('quality_analysis', '0011_reconcile_jira_bug_association_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAnalysisSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('jira_browse_prefix', models.CharField(default='http://172.31.119.34:8080/browse/', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quality analysis settings',
                'verbose_name_plural': 'Quality analysis settings',
                'db_table': 'quality_analysis_settings',
            },
        ),
        migrations.RunPython(seed_quality_analysis_settings, migrations.RunPython.noop),
    ]
