# Generated by Django 4.2.7 on 2026-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_fix_missing_element_order_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='action_type',
            field=models.CharField(choices=[('click', '点击'), ('fill', '输入文本'), ('getText', '获取文本'), ('waitFor', '等待元素'), ('hover', '悬停'), ('scroll', '滚动'), ('screenshot', '截图'), ('assert', '断言'), ('wait', '等待'), ('enterIframe', '进入iframe'), ('exitIframe', '退出iframe'), ('switchTab', '切换标签页')], max_length=20, verbose_name='操作类型'),
        ),
    ]
